name: Build Deploy and Run Docker

on:
  push:
    branches:
      - deploy
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deployd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clone repo secundario con archivos VPN
        run: |
          git clone https://${{ secrets.USER_GI }}:${{ secrets.TOKEN_GI }}@${{ secrets.REPOSITORY }}
        env:
          GH_TOKEN: ${{ secrets.TOKEN_GI }}

      - name: Instalar OpenVPN
        run: sudo apt-get install openvpn -y

      - name: Mover configuración de VPN a /etc/openvpn
        run: |
          sudo mv ./dataSSHScanLis/ /etc/openvpn/

      - name: Iniciar OpenVPN con configuración y credenciales
        run: |
          cd /etc/openvpn/dataSSHScanLis
          sudo openvpn --config ${{ secrets.CERT }} &
      
      - name: Esperar a que la VPN se conecte
        run: sleep 15
      - name: Verificar rutas activas
        run: |
          ip route
          ip a
      - name: Verificar conectividad
        run: ping -c 4 ${{ secrets.SSH_HOST }}
      - name: Despliegue por SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.WORK_DIR }}
            git pull
            git checkout deploy
            docker compose down
            docker compose build -q
            docker compose up -d
